apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: webhook-receiver
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- buildconfig.yaml
- imagestream.yaml

configurations:
  - nameReference.yaml

secretGenerator:
  - name: github-buildconfig
    literals:
    - WebHookSecretKey=UPDATE_IN_OVERLAY
  - name: webhook-receiver
    literals:
    - FLASK_GITHUB_WEBHOOK_SECRET=UPDATE_IN_OVERLAY
    - FLASK_SLACK_WEBHOOK_URL=UPDATE_IN_OVERLAY
