apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: webhook-receiver

resources:
- ../../base

patches:
- patch: |
    apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: webhook-receiver
    spec:
      source:
        git:
          uri: https://github.com/YOUR_USERNAME/webhook-example.git

secretGenerator:
- name: github-buildconfig
  envs:
  - github-buildconfig.env
- name: webhook-receiver
  envs:
  - webhook-receiver.env
