apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-receiver
spec:
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
    spec:
      containers:
        - name: webhook-receiver
          image: webhook-receiver:latest
          envFrom:
            - secretRef:
                name: github-notification-secret
          ports:
            - name: http
              containerPort: 8080
